### ISSUE TITLE
Update for Gleam 1.0.0

### ISSUE THREAD

**Issue by philipgiuliani** [aosasona/migrant#4]
The library is not ready for Gleam 1.0 yet! Compilation fails with:

```
error: Inexhaustive patterns
   ┌─ /my_project/build/packages/migrant/src/migrant/filesystem.gleam:69:27
   │
69 │             let migration = case direction {
   │ ╭───────────────────────────^
70 │ │             "up" -> Migration(..migration, up: sql)
71 │ │             "down" -> Migration(..migration, down: sql)
72 │ │           }
   │ ╰───────────^

This case expression does not have a pattern for all possible values.
If is run on one of the values without a pattern then it will crash.

The missing patterns are:

    _
```

**Comment by aosasona** [comment]
Yes, I am aware of this, I have been slowly working on a proper version on the `v1` branch but for those who may want to use this with the RC or just in case I am not done with that before the V1 release (quite busy these days), I will fix the warnings/error, thank you!

**Comment by aosasona** [comment]
This should be fixed now:  https://github.com/aosasona/migrant/pull/5

Let me know if you face any issues with the release before I mark the issue as completed :)

**Comment by philipgiuliani** [comment]
Works perfectly fine now, thanks!
There are a bunch of warnings when compiling the dependency!

```
warning: Deprecated value used
   ┌─ /project/build/packages/migrant/src/migrant/filesystem.gleam:29:37
   │
29 │   use <- bool.guard(when: simplifile.is_directory(path), return: next(path))
   │                                     ^^^^^^^^^^^^^ This value has been deprecated

It was deprecated with this message: Use `verify_is_directory` instead
/project/build/dev/erlang/migrant/_gleam_artefacts/migrant@database.erl:155:29: Warning: a term is constructed, but never used
%  155|                             {ok, nil};
%     |                             ^

/project/build/dev/erlang/migrant/_gleam_artefacts/migrant@database.erl:169:37: Warning: a term is constructed, but never used
%  169|                                     {error,
%     |                                     ^

/project/build/dev/erlang/migrant/_gleam_artefacts/migrant@database.erl:171:45: Warning: a term is constructed, but never used
%  171|                                             <<"Rollback complete, failed to mark migration as applied: "/utf8,
%     |                                             ^

/project/build/dev/erlang/migrant/_gleam_artefacts/migrant@database.erl:180:37: Warning: a term is constructed, but never used
%  180|                                     {error, E@1}
%     |                                     ^
```

**Comment by aosasona** [comment]
Out of curiosity, do you have another version of `simplifile` installed as part of your project itself?

I have only been able to replicate that warning by bumping the simplifile version so it seems the Gleam compiler is probably using the top-level `simplifile` dep in your project if you have one, or one from another project with a more recent version.

![CleanShot 2024-02-19 at 15 23 16@2x](https://github.com/aosasona/migrant/assets/97124713/32375969-7b0d-4f51-a826-b1a3593c757a)

**Comment by philipgiuliani** [comment]
Yes I also have simplifile in my project using the latest version!

**Comment by aosasona** [comment]
I'm unsure why my reply never went through, I've only just realised this. That simplifile warning should be gone in the latest version now!
